name: run-tests

on: [ push ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.3, 8.4 ]
        laravel: [ ^11.0, ^12.0 ]
        dependency-version: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: ^11.0
            testbench: ^9.0
          - laravel: ^12.0
            testbench: ^10.0
        exclude:
          - laravel: ^11.0
            php: 8.4
            dependency-version: prefer-lowest

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --no-scripts
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-scripts

      - name: Execute tests
        run: vendor/bin/pest
